name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-reusable
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    name: "Build and Publish"
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y git llvm clang make lld curl
    - name: "Install cargo-wasix"
      run: |
        cargo install cargo-wasix
    - name: "Build"
      run: |
        cargo wasix build --release
    - name: Setup Wasmer
      uses: wasmerio/setup-wasmer@v3.1
    - name: "Publish"
      run: |
        wasmer publish --registry="wasmer.io" --namespace wasmer --name tantivy --bump --non-interactive --token "${{ secrets.WASMER_CIUSER_PROD_TOKEN }}"
        